name: pagox
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  material_design_icons_flutter: ^4.0.5045
  flutter_sliding_tutorial: ^0.1.0

  flutter_mobx: ^0.3.6
  provider: ^4.0.1
  flutter_svg: ^0.14.0

  cupertino_icons: ^0.1.2
  cloud_firestore: ^0.13.5
  firebase_auth: ^0.16.0
  firebase_core: ^0.4.4+3

dev_dependencies:
  mobx_codegen: ^0.4.0+1
  build_runner: ^1.7.3
  flutter_launcher_name: ^0.0.1
  flutter_launcher_icons: ^0.7.4
  flutter_native_splash: ^0.1.9


  flutter_test:
    sdk: flutter

  # scripts devem ficar aqui abaixo com os comandos para execução

# gera a splash screen
# flutter pub pub run flutter_native_splash:create
flutter_native_splash:
  image: assets/images/launcher/splash.png
  color: "4caf50"
  fill: true

# gera o icone da aplicação
# flutter pub run flutter_launcher_icons:main
flutter_icons:
  ios: true
  android: "launcher_icon" 
  # image_path: "assets/launcher/icone.png"
  image_path_ios: "assets/images/launcher/icon.png"
  image_path_android: "assets/images/launcher/icon.png"
  # adaptive_icon_background: "assets/launcher/background.png"
  # adaptive_icon_foreground: "assets/launcher/foreground.png"

# gera o nome da aplicação
# flutter pub run flutter_launcher_name:main
flutter_launcher_name:
  name: "PagoX"


flutter:

  uses-material-design: true

  assets:
    - assets/images/pagox_logo_normal.png
    - assets/images/launcher/icon.png
    - assets/images/launcher/splash.png

    - assets/images/tutorial/hollow_circle.svg
    - assets/images/tutorial/tutorial_1.png
    - assets/images/tutorial/tutorial_2.png
    - assets/images/tutorial/tutorial_3.png

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
